apps/works/urls.py
from django.conf.urls import url
from . import views

# SET THE NAMESPACE!
app_name = 'works'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^list/$',views.WorkListView.as_view(),name='list'),
    url(r'^(?P<pk>\d+)/$',views.WorkDetailView.as_view(),name='detail'),
    url(r'^search/$',views.WorkSearchView.as_view(),name='search'),
]

bjServices/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('apps.core.urls', namespace='core')),
    url(r'^services/',include('apps.services.urls', namespace='services')),
    url(r'^works/',include('apps.works.urls', namespace='works')),
    #url(r'^skills/', include('apps.skills.urls', namespace='skills')),
    url(r'^texts/',include('apps.texts.urls', namespace='texts')),
    url(r'^enquiries/', include('apps.enquiries.urls', namespace='enquiries')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/works/models.py
from django.db import models
from django.core.urlresolvers import reverse # For update and create views
from apps.categories.models import Category

# Create your models here.
class Work(models.Model):

    category = models.ForeignKey(Category, related_name='+', on_delete=models.CASCADE)
    before_photo_1 = models.ImageField(upload_to='img', null=True, blank=True)
    before_photo_2 = models.ImageField(upload_to='img', null=True, blank=True)
    after_photo_1 = models.ImageField(upload_to='img', null=True, blank=True)
    after_photo_2 = models.ImageField(upload_to='img', null=True, blank=True)
    title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    date = models.DateField(null=True, blank=True)
    client = models.CharField(max_length=100, null=True, blank=True)
    link = models.CharField(max_length=150, null=True, blank=True)
    more_photo_1 = models.ImageField(upload_to='img', null=True, blank=True)
    more_photo_2 = models.ImageField(upload_to='img', null=True, blank=True)
    more_photo_3 = models.ImageField(upload_to='img', null=True, blank=True)
    more_photo_4 = models.ImageField(upload_to='img', null=True, blank=True)
    more_photo_5 = models.ImageField(upload_to='img', null=True, blank=True)


    def __str__(self):
        return self.title

apps/works/views.py
from django.views.generic import (View,TemplateView,
                                ListView,DetailView,
                                CreateView,DeleteView,
                                UpdateView, FormView)

from apps.texts.models import Text
from apps.works.models import Work
from apps.categories.models import Category
from apps.core.models import Company

from apps.categories.models import Category

from django.db.models import Q
from django.shortcuts import redirect, render

# Create your views here.

#CRUD Views

class WorkListView(ListView):
    # If you don't pass in this attribute,
    # Django will auto create a context name
    # for you with object_list!
    # Default would be 'school_list'

    # Example of making your own:
    context_object_name = 'works'
    #model = Work
    queryset = Work.objects.all()

    def get_context_data(self,**kwargs):
        context  = super().get_context_data(**kwargs)
        context['texts'] = Text.objects.all()
        context['categories'] = Category.objects.all()
        context['companies'] = Company.objects.filter(name__icontains='BJ Services')
        return context

class WorkDetailView(DetailView):
    context_object_name = 'work_details'
    model = Work
    template_name = 'works/work_details.html'

class WorkSearchView(ListView):
    template_name = 'works/search_result.html'
    model = Work
    context_object_name = 'works'
    fieldsData = {}

    def get_queryset(self):
        #add fieldData to context dictionary
        self.fieldsData['name'] = self.request.GET['name']
        self.fieldsData['city'] = self.request.GET['city']
        self.fieldsData['state'] = self.request.GET['state']
        self.fieldsData['country'] = self.request.GET['country']

        name = self.request.GET['name']
        city = self.request.GET['city']
        state = self.request.GET['state']
        country = self.request.GET['country']

        if not self.model.objects.filter(city__icontains=city):
            city = ''
        if not self.model.objects.filter(state__icontains=state):
            state = ''
        if not self.model.objects.filter(country__icontains=country):
            country = ''

        return self.model.objects.filter(name__icontains=name, city__icontains=city, state__icontains=state, country__icontains=country)

    #def get_context_data(self,**kwargs):
        #context  = super().get_context_data(**kwargs)
        #congregation_search_form = forms.CongregationSearchForm()
        #context['congregation_search_form'] = congregation_search_form
        #context['fieldsData'] = self.fieldsData
        #return context

apps/works/templates/works/work_details.html
{% extends "core/base.html" %}
{% load staticfiles %}

{% block body_block %}

<!-- Portfolio Grid Section -->
<section id="portfolio" class="bg-light-gray">
<div class="container">
    <div class="row">
        <div class="col-lg-12 text-center">
            <h3 style="margin-top:-70px">{{work_details.title}}</h3>
        </div>
    </div>
    <div class="row" style="margin:auto;">
        <div class="col-md-4 col-sm-6 portfolio-item">
            <a href="{%url 'works:detail' pk=work_details.pk %}">
                <img src="/media/{{work_details.main_photo}}" class="img-responsive" alt="">
            </a>
            <div class="portfolio-caption">
              <p class="text-muted">Category: {{work_details.category}}</p>
              <p class="text-muted">Date: {{work_details.date}}</p>
              <p class="text-muted">Client: {{work_details.client}}</p>
              <p class="text-muted"><a href="{{work_details.link}}" target="blank">Website Link</a></p>
            </div>
        </div>
    </div>
</div>
</section>


{% endblock %}

apps/works/templates/works/work_list.html
{% extends "core/base.html" %}
{% load staticfiles %}
{% load bootstrap %}

{% block title_block %}PROJECTS{% endblock %} 
{% block body_block %}

<div class="theme-page padding-bottom-66">
    <h2 class="box-header" style="margin-top:35px;">OUR PROJECTS</h2>
    <div class="clearfix bj-gallery">
        <div class="row">
            <ul class="tabs-navigation small gray isotope-filters margin-top-70">
                <li><a class="selected" href="#filter-*" title="All Projects">All Projects</a></li>
                {% for category in categories %}
                <li><a href="#filter-{{category.name}}" title="{{category.name}}">{{category.name}}</a></li>
                {% endfor %}
            </ul>
            <ul class="projects-list isotope">
                {% for work in works %}
                    {% if work.before_photo_1 %}
                    <li class="{{work.category}}">
                        <a href="#" title="{{work.category}}">
                            <img class="imgpg" src="../../../../media/{{work.before_photo_1}}" alt="">
                        </a>
                        <div class="view align-center">
                            <div class="vertical-align-table">
                                <div class="vertical-align-cell">
                                    <p class="description">{{work.category}}</p>
                                    <a class="more simple" href="../../../../media/{{work.before_photo_1}}" class="lightbox" title="{{work.category}}">ZOOM IN</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    {% endif %}
                    {% if work.before_photo_2 %}
                    <li class="{{work.category}}">
                        <a href="#" title="{{work.category}}">
                            <img src="../../../../media/{{work.before_photo_2}}" alt="">
                        </a>
                        <div class="view align-center">
                            <div class="vertical-align-table">
                                <div class="vertical-align-cell">
                                    <p class="description">{{work.category}}</p>
                                    <a class="more simple" href="../../../../media/{{work.before_photo_2}}" class="lightbox" title="{{work.category}}">ZOOM IN</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    {% endif %}
                    {% if work.after_photo_1 %}
                    <li class="{{work.category}}">
                        <a href="#" title="{{work.category}}">
                            <img src="../../../../media/{{work.after_photo_1}}" alt="">
                        </a>
                        <div class="view align-center">
                            <div class="vertical-align-table">
                                <div class="vertical-align-cell">
                                    <p class="description">{{work.category}}</p>
                                    <a class="more simple" href="../../../../media/{{work.after_photo_1}}" class="lightbox" title="{{work.category}}">ZOOM IN</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    {% endif %}
                    {% if work.after_photo_2 %}
                    <li class="{{work.category}}">
                        <a href="#" title="{{work.category}}">
                            <img src="../../../../media/{{work.after_photo_2}}" alt="">
                        </a>
                        <div class="view align-center">
                            <div class="vertical-align-table">
                                <div class="vertical-align-cell">
                                    <p class="description">{{work.category}}</p>
                                    <a class="more simple" href="../../../../media/{{work.after_photo_2}}" class="lightbox" title="{{work.category}}">ZOOM IN</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

{% endblock %}