apps/core/urls.py
from django.conf.urls import url,include
from . import views

# SET THE NAMESPACE!
app_name = 'core'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

apps/enquiries/urls.py
from django.conf.urls import url
from . import views

# SET THE NAMESPACE!
app_name = 'enquiries'

urlpatterns = [
    url(r'^email/$',views.send_email_view,name='email'),
]

apps/texts/urls.py
from django.conf.urls import url
from . import views

# SET THE NAMESPACE!
app_name = 'texts'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^list/$',views.TextListView.as_view(),name='list'),
    url(r'^(?P<pk>\d+)/$',views.TextDetailView.as_view(),name='detail'),
    url(r'^search/$',views.TextSearchView.as_view(),name='search'),
]

bjServices/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('apps.core.urls', namespace='core')),
    url(r'^services/',include('apps.services.urls', namespace='services')),
    url(r'^works/',include('apps.works.urls', namespace='works')),
    #url(r'^skills/', include('apps.skills.urls', namespace='skills')),
    url(r'^texts/',include('apps.texts.urls', namespace='texts')),
    url(r'^enquiries/', include('apps.enquiries.urls', namespace='enquiries')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/models.py
from django.db import models

class Company(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=150, null=True, blank=True)
    phone = models.CharField(max_length=100)
    description = models.TextField()
    slider_img_1 = models.ImageField(upload_to='img', null=True, blank=True)
    slider_img_2 = models.ImageField(upload_to='img', null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Companies"

apps/core/views.py
from apps.enquiries import forms

from django.views.generic import ListView
from apps.services.models import Service
from apps.texts.models import Text
from apps.works.models import Work
from apps.skills.models import Skill
from apps.categories.models import Category
from apps.reviews.models import Review
from apps.enquiries.models import Enquiry
from apps.core.models import Company
from apps.teammembers.models import TeamMember


class IndexView(ListView):
    context_object_name = 'texts'
    #model = Work
    template_name = 'core/index.html'
    queryset = Text.objects.all()

    def get_context_data(self,**kwargs):
        context  = super().get_context_data(**kwargs)
        context['reviews'] = Review.objects.all()
        context['services'] = Service.objects.all()[:3]
        context['works'] = Work.objects.order_by('id').reverse()[:4]
        context['skills'] = Skill.objects.all()
        context['categories'] = Category.objects.all()
        context['enquiries'] = Enquiry.objects.all()
        context['companies'] = Company.objects.filter(name__icontains='BJ Services')
        context['teammembers'] = TeamMember.objects.all()
        context['contact_form'] = forms.ContactForm
        return context

apps/core/templates/core/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load bootstrap %}
<html>
	<head>
		<title>BJ Services | {% block title_block %}{% endblock %}</title>
		<!--meta-->
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.2" />
		<meta name="format-detection" content="telephone=no" />
		<meta name="keywords" content="Construction, Renovation" />
		<meta name="description" content="Responsive Construction Renovation Template" />
		<!--slider revolution-->
		<link rel="stylesheet" type="text/css" href="{% static 'rs-plugin/css/settings.css' %}" media="screen" />
		<!--style-->
		<link href='//fonts.googleapis.com/css?family=Raleway:100,300,400,500,600,700,900' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" type="text/css" href="{% static 'style/reset.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'style/superfish.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'style/prettyPhoto.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'style/jquery.qtip.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'style/style.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'style/animations.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'style/responsive.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'style/odometer-theme-default.css' %}">
		
		<!--fonts-->
		<link rel="stylesheet" type="text/css" href="{% static 'fonts/streamline-small/styles.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'fonts/streamline-large/styles.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'fonts/template/styles.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'fonts/social/styles.css' %}">
		<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

		<!-- photo gallery slider -->
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.css">
   
	</head>
	<body>
		<div class="site-container">
			<div class="header-top-bar-container clearfix">
				<div class="header-top-bar">
					<ul class="contact-details clearfix">
						<li class="template-phone">
							<a href="tel:+13474627620">347-462-7620</a>
						</li>
						<li class="template-mail">
							<a href="mailto:bjservices@gmail.com">bjservices@gmail.com</a>
						</li>
						<li class="template-clock">
							Mon - Fri: 08.00 - 17.00
						</li>
					</ul>
				</div>
				<a href="#" class="header-toggle template-arrow-up"></a>
			</div>
			<!--<div class="header-container">-->
			<div class="header-container sticky">
				<div class="vertical-align-table column-1-1">
					<div class="header clearfix">
						<div class="logo vertical-align-cell">
							<h1>
								<a href="{% url 'core:index' %}" title="BJServices">BJ Services</a>
							</h1>
						</div>
						<a href="#" class="mobile-menu-switch vertical-align-cell">
							<span class="line"></span>
							<span class="line"></span>
							<span class="line"></span>
						</a>
						<div class="menu-container clearfix vertical-align-cell">
							<nav>
								<ul class="sf-menu">
									<li class="{% if request.path == '/' %}selected{% endif %}">
										<a href="{% url 'core:index' %}" title="Home">
											HOME
										</a>
									</li>
									<li class="{% if request.path == '/services/list/' %}selected{% endif %}">
										<a href="{% url 'services:list' %}" title="Services">
											SERVICES
										</a>
										<ul>
											{% for category in categories %}
											<li>
												<a href="{% url 'services:list' %}" title="{{category.title}}">
													{{category.name}}
												</a>
											</li>
											{% endfor %}
										</ul>
									</li>
									<li class="{% if request.path == '/works/list/' %}selected{% endif %}">
										<a href="{% url 'works:list' %}" title="Projects">
											PROJECTS
										</a>
									</li class="{% if request.path == '/enquiries/email/' %}selected{% endif %}">
									<li class="left-flyout">
										<a href="{% url 'enquiries:email' %}" title="Contact">
											CONTACT
										</a>
									</li>
								</ul>
							</nav>
							<div class="mobile-menu-container">
								<div class="mobile-menu-divider"></div>
								<nav>
									<ul class="mobile-menu collapsible-mobile-submenus">
										<li class="{% if request.path == '/' %}selected{% endif %}">
											<a href="{% url 'core:index' %}" title="Home">
												HOME
											</a>
										</li>
										<li class="{% if request.path == '/services/list/' %}selected{% endif %}">
											<a href="{% url 'services:list' %}" title="Services">
												SERVICES
											</a>
											<a href="#" class="template-arrow-menu"></a>
											<ul>
												{% for category in categories %}
												<li>
													<a href="{% url 'services:list' %}" title="{{category.title}}">
														{{category.name}}
													</a>
												</li>
												{% endfor %}
											</ul>
										</li>
										<li class="{% if request.path == '/works/list/' %}selected{% endif %}">
											<a href="{% url 'works:list' %}" title="Projects">
												PROJECTS
											</a>
										</li>
										<li class="left-flyout {% if request.path == '/enquiries/email/' %}selected{% endif %}">
											<a href="{% url 'enquiries:email' %}" title="Contact">
												CONTACT
											</a>
										</li>
									</ul>
								</nav>
							</div>
						</div>
					</div>
				</div>
            </div>
            
            <!-- other pages content goes here -->
            {% block body_block %}
            {% endblock %}

            <div class="row yellow full-width padding-top-bottom-30">
				<div class="row">
					<div class="column column-1-3">
						<ul class="contact-details-list">
							<li class="sl-small-phone">
								<p>Phone:<br>
								<a href="tel:+13474627620">347-462-7620</a></p>
							</li>
						</ul>
					</div>
					<div class="column column-1-3">
						<ul class="contact-details-list">
							<li class="sl-small-location">
								<p>New Jersey<br>
								New York</p>
							</li>
						</ul>
					</div>
					<div class="column column-1-3">
						<ul class="contact-details-list">
							<li class="sl-small-mail">
								<p>E-mail:<br>
								<a href="mailto:bjservices@gmail.com">bjservices@gmail.com</a></p>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="footer row align-center padding-top-bottom-30">
				<span class="copyright footer">© Copyright 2018 BJ Services All Rights Reserved</a></span>
			</div>
		</div>
		<a href="#top" class="scroll-top animated-element template-arrow-up" title="Scroll to top"></a>
		<!--js-->
		<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery-migrate-1.4.1.min.js' %}"></script>
		<!--slider revolution-->
		<script type="text/javascript" src="{% static 'rs-plugin/js/jquery.themepunch.tools.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'rs-plugin/js/jquery.themepunch.revolution.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.ba-bbq.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery-ui-1.11.4.custom.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.ui.touch-punch.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.isotope.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.easing.1.3.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.carouFredSel-6.2.1-packed.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.touchSwipe.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.transit.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.hint.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.costCalculator.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.parallax.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.qtip.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.blockUI.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/odometer.min.js' %}"></script>
        <!-- Slider Revolution -->
		<script type="text/javascript" src="{% static 'rs-plugin/js/extensions/revolution.extension.video.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'rs-plugin/js/extensions/revolution.extension.slideanims.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'rs-plugin/js/extensions/revolution.extension.actions.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'rs-plugin/js/extensions/revolution.extension.layeranimation.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'rs-plugin/js/extensions/revolution.extension.kenburn.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'rs-plugin/js/extensions/revolution.extension.navigation.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'rs-plugin/js/extensions/revolution.extension.migration.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'rs-plugin/js/extensions/revolution.extension.parallax.min.js' %}"></script>

		<!-- photo gallery slider -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script> 
		<script>
			baguetteBox.run('.bj-gallery');
		</script>
	</body>
</html>

apps/core/templates/core/index.html
{% extends "core/base.html" %}
{% load staticfiles %}
{% load bootstrap %}

{% block title_block %}Home{% endblock %} 

{% block body_block %}

<!-- Slider Revolution -->
<div class="revolution-slider-container">
    <div class="revolution-slider">
        <ul style="display: none;">

            <!-- SLIDE 1 -->
            <li data-transition="fade" data-masterspeed="500" data-slotamount="1" data-delay="6000">
                <!-- MAIN IMAGE -->
                <img src="{% static 'images/slider/image_02.jpg' %}" alt="slidebg2" data-bgfit="cover">
                <!-- LAYERS -->
                <!-- LAYER 01 -->
                <div class="tp-caption"
                    data-frames='[{"delay":500,"speed":1200,"from":"x:40;o:0;","ease":"easeInOutExpo"},{"delay":"wait","speed":500,"to":"o:0;","ease":"easeInOutExpo"}]'
                    data-x="0"
                    data-y="140"
                    >
                    <!--data-start="500"
                    data-transform_in="x:40;y:0;o:0;s:1200;e:easeInOutExpo;"
                    data-transform_out="x:0;y:0;o:0;s:500;e:easeInOutExpo;"-->
                    
                    <div class="slider-content-box">
                        <h2><a href="{% url 'services:list' %}" title="Services">PROFESSIONAL RENOVATION SERVICES</a></h2>
                        <p>We combine quality workmanship, superior knowledge and low prices to provide you with service unmatched by our competitors.</p>
                        <a target="_top" class="more simple" href="{% url 'enquiries:email' %}" title="CONTACT US">CONTACT US</a>
                    </div>
                </div>
            </li>
            
            <!-- SLIDE 2 -->
            <li data-transition="fade" data-masterspeed="500" data-slotamount="1" data-delay="6000">
                <!-- MAIN IMAGE -->
                <img src="{% static 'images/slider/money-saving.jpg' %}" alt="slidebg3" data-bgfit="cover">
                <!-- LAYERS -->
                <!-- LAYER 01 -->
                <div class="tp-caption"
                    data-frames='[{"delay":500,"speed":1200,"from":"x:40;o:0;","ease":"easeInOutExpo"},{"delay":"wait","speed":500,"to":"o:0;","ease":"easeInOutExpo"}]'
                    data-x="0"
                    data-y="140"
                    >
                    <!--data-start="500"
                    data-transform_in="x:40;y:0;o:0;s:1200;e:easeInOutExpo;"
                    data-transform_out="x:0;y:0;o:0;s:500;e:easeInOutExpo;"-->
                    
                    <div class="slider-content-box">
                        <h2><a href="service_household_repairs.html" title="HOUSEHOLD REPAIRS">YOUR MOST AFFORDABLE CONTRACTOR</a></h2>
                        <p>We have the experience, personel and resources to make the project run smoothly. We can ensure a job is done on time.</p>
                        <a target="_top" class="more simple" href="{% url 'enquiries:email' %}" title="CONTACT US">CONTACT US</a>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>
<!--/-->

<div class="theme-page">
    <div class="clearfix">

        <div class="row page-margin-top-section padding-bottom-66">
            <h2 class="box-header">WHY CHOOSE BJ SERVICES</h2>
            {% for company in companies %}
            <p class="description align-center">{{company.description}}</p>
            {% endfor %}
            <div class="row page-margin-top">
                <div class="column column-1-3">
                    <ul class="features-list big">
                        <li class="sl-large-house-1">
                            <div class="ornament"></div>
                            <h4 class="box-header page-margin-top">OVER 15 YEARS EXPERIENCE</h4>
                            <p>Morbi nulla tortor, dignissim est node cursus euismod est arcu. Nomad at vehicula novum justo magna.</p>
                        </li>
                    </ul>
                </div>
                <div class="column column-1-3">
                    <ul class="features-list big">
                        <li class="sl-large-eco">
                            <div class="ornament"></div>
                            <h4 class="box-header page-margin-top">BEST MATERIALS</h4>
                            <p>Morbi nulla tortor, dignissim est node cursus euismod est arcu. Nomad at vehicula novum justo magna.</p>
                        </li>
                    </ul>
                </div>
                <div class="column column-1-3">
                    <ul class="features-list big">
                        <li class="sl-large-garage">
                            <div class="ornament"></div>
                            <h4 class="box-header page-margin-top">PROFESSIONAL STANDARDS</h4>
                            <p>Morbi nulla tortor, dignissim est node cursus euismod est arcu. Nomad at vehicula novum justo magna.</p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="row full-width gray page-padding-top-section">
            <div class="row">
                <h2 class="box-header">SERVICES</h2>
                <p class="description align-center">With over 15 years experience and real focus on customer satisfaction, you can rely on us for your next renovation,<br>driveway sett or home repair. We provide a professional service for private and commercial customers.</p>
                <ul class="services-list clearfix page-margin-top">
                    {% for service in services%}
                    <li>
                        <a href="#" title="Interior Renovation">
                            <img src="../../../../media/{{service.image}}" alt="">
                        </a>
                        <h4 class="box-header"><a href="#" title="Interior Renovation">{{service.title}}</a></h4>
                        <p>{{service.description}}</p>
                    </li>
                    {% endfor %}
                </ul>
                <div class="align-center margin-top-67 padding-bottom-87">
                    <a class="more" href="{% url 'services:list' %}" title="VIEW ALL SERVICES">VIEW ALL SERVICES</a>
                </div>
            </div>
        </div>
        <div class="row full-width page-margin-top-section">
            <div class="row">
                <h2 class="box-header">RECENT PROJECTS</h2>
                <p class="description align-center">Here are a few of many projects we have completed for our customers. We provide a professional service<br>which includes consultation, free estimate, design, supply of materials and installation.</p>
            </div>	
            <ul class="projects-list clearfix page-margin-top">
                {% for work in works %}
                <li class="projectsFrame">
                    <a href="{% url 'works:list' %}" title="{{work.category}}">
                        <img class="imgp" src="../../../../media/{{work.after_photo_1}}" alt="">
                    </a>
                    <div class="view align-center">
                        <div class="vertical-align-table">
                            <div class="vertical-align-cell">
                                <p class="description">{{work.category}}</p>
                                <a class="more simple" href="{% url 'works:list' %}" title="MORE PICTURES">MORE PICTURES</a>
                            </div>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="row full-width padding-top-54 padding-bottom-61 align-center">
            <h3><a class="more" href="{% url 'works:list' %}" title="MORE PICTURES">VIEW MORE PICTURES</a></h3>
        </div>
        <!--<div class="row gray full-width padding-top-bottom-50">
            <div class="row">
                <div class="column column-1-2 align-right padding-top-7">
                    <h3>EXPLORE OUR PROJECTS</h3>
                </div>
                <div class="column column-1-2">
                    <a class="more float" href="projects.html" title="VIEW ALL PROJECTS">VIEW ALL PROJECTS</a>
                </div>
            </div>
        </div>-->
        <div class="row full-width padding-top-70 padding-bottom-66 parallax parallax-1">	
            <h2 class='reviewsH2'>CUSTOMER REVIEWS</h2>
            <div class="row testimonials-container">
                <a href="#" class="slider-control left template-arrow-left-1"></a>
                <ul class="testimonials-list">
                    {% for review in reviews %}
                    <li class="sl-small-conversation">
                        <div class="ornament"></div>
                        <p>{{review.content}}</p>
                        <div class="author">{{review.name}}</div>
                        <div class="author-details">{{review.position}} at {{review.company}}</div>
                    </li>
                    {% endfor %}
                </ul>
                <a href="#" class="slider-control right template-arrow-left-1"></a>
            </div>
        </div>
    </div>
</div>

{% endblock %}